### ISSUE TITLE
EPS 0.6.0 and Reaper frequently crashes when importing ADM files

### ISSUE THREAD

**Issue by WernerBleisteiner** [ebu/ear-production-suite#12]
MacOS 10.14.6  Reaper 6.12. - 6.14 / EPS 0.6.0.

Starting a new project in freshly started Reaper. 
Open "Create from ADM using EAR" and selecting file.
Import starts and writes files into folder "Reaper Media".
100% - EAR panner plugins briefly appear - and Reaper crashes.

Simple test files (EBU IO) seem to work .
Some crash reports attached
[Reaper-EPS-Crahes.zip](https://github.com/ebu/ear-production-suite/files/5372233/Reaper-EPS-Crahes.zip)

**Comment by firthm01** [comment]
Hi Werner - Thank you for the report
I've had a look at the crash logs and can't see anything obvious in the function where the crash seems to stem from. If you have any non-sensitive example files you are able to share with us to recreate the crash, that could make it easier to solve. If so, you could send us a link at `ear-production-suite-admins@list.ebu.ch` if you'd rather not share publicly in this issue.

**Comment by WernerBleisteiner** [comment]
Just tried to open the "Meditation Scene" ADM Chris has recently shared. Same behaviour: After import Reaper 6.15 crashes immediately when building the windows. Found this in Console:

`Oct 21 12:35:23 MacBook-Pro-3 REAPER[22129]: assertion failed: 18G103: libxpc.dylib + 90677 [7DEE2300-6D8E-3C00-9C63-E3E80D56B0C4]: 0x89
Oct 21 12:35:23 MacBook-Pro-3 com.apple.xpc.launchd[1] (com.getdropbox.dropbox.garcon.63016607-5B7A-48AD-B66E-6F8D8735709B[22146]): Caller wanted oneshot behavior for pre-existing instance: caller = REAPER
Oct 21 12:35:23 MacBook-Pro-3 com.apple.xpc.launchd[1] (com.owncloud.desktopclient.FinderSyncExt.41FC032D-7E37-4DA3-B8CB-41EFFA460E3E[22147]): Caller wanted oneshot behavior for pre-existing instance: caller = REAPER
Oct 21 12:35:30 MacBook-Pro-3 REAPER[22129]: objc[22129]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff97baa3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x110bcdf50). One of the two will be used. Which one is undefined.
Oct 21 12:35:57 MacBook-Pro-3 com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000002b.REAPER[22129]): Service exited due to SIGSEGV | sent by exc handler[22129]`

**Comment by WernerBleisteiner** [comment]
Found out that the issue must be related to something within the reaper.ini. Deleting the old one and let Reaper create a new one fixes this issue. Couldn't find out (yet) which of the entries let the ADM import crash. I attach the corrupt ini here, if anybody wants to check that possible incompatibility. 
[reaper-corrupt.ini.zip](https://github.com/ebu/ear-production-suite/files/5553232/reaper-corrupt.ini.zip)
