### ISSUE TITLE
Moving from EPS 0.5.0 to 0.6.0 - ist there an easy way to preserve/mode automation data for objects?

### ISSUE THREAD

**Issue by WernerBleisteiner** [ebu/ear-production-suite#13]
Just moved a session made in EPS 0.5.0 to 0.6.0. Unfortunately, the new plugins are not recognised. Not a bis job to rework for DiectSpeakers, Monitoring and Scene pi. But there's quite a lot of positioning and other parameters in the Object plugin. Unformtunately the tracks are not showing what is what (azimuth, elevation....distance.....etc.) Bit of a guessing when want to move the lines to the respective ones of the new version.
Is there a little bit easier way to get that done?

![ss-Reaper-EPS-Object-Automation](https://user-images.githubusercontent.com/22868982/96113467-81ec2000-0ee4-11eb-8b33-4c8cb44b28b5.png)

**Comment by firthm01** [comment]
It's a hack, but you can do a find/replace in your .rpp file;

find: `656172205564746d`, replace with: `4542552045505320`
find: `4242432041444D20`, replace with: `4542552041444d65`

Hopefully that should work for you - you might want to take a copy of your .rpp file first.

**Comment by WernerBleisteiner** [comment]
Thanks, Matt. That looks fairly geeky. But I'll try;)

**Comment by WernerBleisteiner** [comment]
What a fun hack. It worked! Thanks. Only had to use the first - the other id was not found in my file.

**Comment by WernerBleisteiner** [comment]
P.S.  If  the session was created with "EPS early access", you need additionally
	
 find: EAR Object (ear) ,  replace  with: EAR Object (EBU)
