### ISSUE TITLE
Reaper 6.15 crash ADM Export BED Channel Layout 7.1.2

### ISSUE THREAD

**Issue by roko0206** [ebu/ear-production-suite#21]
I get a Reaper crash when i do an ADM render export with the BED Channel Layout 7.1.2 This under macOS and Windows. BED Channel Layout 5.1.2, 5.1.4 und 7.1.4 ist working. 
![image](https://user-images.githubusercontent.com/74139611/98465574-19821d00-21ca-11eb-8359-9ff473d0e954.png)

**Comment by WernerBleisteiner** [comment]
Guess I just encountered the same issue while importing a full-blown Dolby ADM. 
Attempted to solve this by building anew from main (https://github.com/ebu/ear-production-suite/pull/112).
But it doesn't. 

[REAPER-DOLBY-ADM-import-edit-TEST-v2-edit_5-reverted712_2.RPP.zip](https://github.com/ebu/ear-production-suite/files/7200946/REAPER-DOLBY-ADM-import-edit-TEST-v2-edit_5-reverted712_2.RPP.zip)
