### ISSUE TITLE
Reaper will support 128-channel bussing: EPS to follow?

### ISSUE THREAD

**Issue by Kurville** [ebu/ear-production-suite#244]
Reaper's next release will likely support 128-channel tracks and bussing. https://forum.cockos.com/showthread.php?t=277860

Will EPS be updated to use the new feature?

**Comment by firthm01** [comment]
Hi,
Yes, we're aiming to support it in the next few months. We don't have a firm timescale yet as there are some other things in the way, but this is definitely one of the higher-priority tasks for the EPS.

**Comment by WernerBleisteiner** [comment]
Very much in favour of this, as this opens a perspective to import complex 'Dolby-ADM" files (ITU-R BS.2076-0) and get full internal routing going

**Comment by firthm01** [comment]
Changes now in main. Will be in next release.

**Comment by troullll** [comment]
ear objects routing is limited by 64

**Comment by firthm01** [comment]
> ear objects routing is limited by 64

Hi, could you check your object plugin version (bottom right of plugin GUI) and that you're definitely running REAPER v7.0 or greater? Just tested on my machine with v1.10b and REAPER v7.0 and I can route any channel up to 128 from the object plugin.
