### ISSUE TITLE
Extension causes REAPER crash with Language Pack installed

### ISSUE THREAD

**Issue by firthm01** [ebu/ear-production-suite#25]
This is likely because of the way we find a position to insert our own menu items.

### **Some fix notes;**

Firstly, when this happens, it should fail gracefully and perhaps display a message box to notify the user. (Note that for MacOS we can use `MessageBox` but for Windows we must use `winhelpers::NonBlockingMessageBox` otherwise the user gets stuck on the splash screen)

The REAPER API has a function to translate a string: `const char* LocalizeString(const char* src_string, const char* section, int flagsOptional )` - this should mean we can use the existing logic after translation.

---

Other notes I made, before realising the above function existed;

- If a language pack is set to always be used, then the `langpack` key in `reaper.ini` will be set and point to the language pack in use. However, we can't rely on that. REAPER can be configured to ask on each start-up, in which case `langpack` is never set.
- There doesn't seem to be anything in the API to determine the pack currently in use.
- A language pack attaches a string to an ID (see https://www.reaper.fm/langpack/index.php#langpack_dev ) - this ID is a FNV164 hash of the original, null-terminated English text.

**Comment by firthm01** [comment]
The above two commits will need reverting when this issue is resolved (warnings on website and on repo README)

**Comment by merktj** [comment]
The `const char* LocalizeString(const char* src_string, const char* section, int flagsOptional ` function is not available in the currently used [API v5.961/x64](https://github.com/ebu/ear-production-suite/blob/main/reaper-adm-extension/src/reaper_adm/reaper_plugin_functions.h).
In the [latest SDK](https://github.com/justinfrankel/reaper-sdk/blob/main/sdk/reaper_plugin_functions.h) version it's there.

Is there a reason for using the old API, respectively does something speak against updating it?

**Comment by merktj** [comment]
The `const char* LocalizeString(const char* src_string, const char* section, int flagsOptional` got introduced with [API v6.10](https://forum.cockos.com/showthread.php?t=236133) and updating the API would not ensure backwards compatibility.

The probable easiest way to work around this is to insert the menues directly by their position index, without searching the index by string comparisons.

**Comment by firthm01** [comment]
The reason we avoided using indexes originally is that anything else that adds menu options itself would throw this out (including new features in future versions of REAPER.) 
I think hard-coded indexes would be a good fallback however for when the search strings are not found (rather than the crash it currently causes!) This way, at least if those searched menu items disappear/change name in future versions of REAPER, we still have some way to present our options even if they might end up in the wrong position. 
It would probably be good to put in some asserts in there (or some other method of flagging an issue) so that if the search strings are found but the index does not match the hard-coded fallback index, we will be alerted to it and can update them.
