### ISSUE TITLE
Dynamics objects

### ISSUE THREAD

**Issue by dblanchemain** [ebu/ear-production-suite#286]
Hello
I developed a javascript function to save the audio objects of my application in ADM format but when defining dynamic objects ear does not render the movement of the object width ear-render -s 0+5+0.

ear-utils dump-axml :

<?xml version="1.0" encoding="UTF-8"?><ebuCoreMain xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns="urn:ebu:metadata-schema:ebuCore" xml:lang="en">
  <coreMetadata>
    <title typeLabel="FileTitle">
      <dc:title xml:lang="en">projet2</dc:title>
    </title>
    <creator>
      <organisationDetails>
        <organisationName>KandiskyScore</organisationName>
      </organisationDetails>
    </creator>
    <description typeLabel="Description" typeLink="http://www.ebu.ch/metadata/cs/ebu_DescriptionTypeCodeCS.xml#1">
      <dc:description>comment: projet2 (1 stereo tracks    1 objets)
    </dc:description>
    </description>
    <date>
      <created startDate="24082024"/>
    </date>
    <format>
            <audioFormatExtended>
 <audioObject audioObjectID="AO_1001" audioObjectName="Object 1" start="00:00:03.16667" duration="00:00:02.35433">
                                  <audioPackFormatIDRef>AP_00031001</audioPackFormatIDRef>
                                  <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>
                                </audioObject>
 <audioObject audioObjectID="AO_1002" audioObjectName="Object 2" start="00:00:03.16667" duration="00:00:02.35433">
                                  <audioPackFormatIDRef>AP_00031002</audioPackFormatIDRef>
                                  <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>
                                </audioObject>
<audioPackFormat audioPackFormatID="AP_00031001" audioPackFormatName="objet 1" typeLabel="0003" typeDefinition="Objects">
          <audioChannelFormatIDRef>AC_00031001</audioChannelFormatIDRef>
        </audioPackFormat>
<audioPackFormat audioPackFormatID="AP_00031002" audioPackFormatName="objet 2" typeLabel="0003" typeDefinition="Objects">
          <audioChannelFormatIDRef>AC_00031002</audioChannelFormatIDRef>
        </audioPackFormat>
<audioChannelFormat audioChannelFormatID="AC_00031001" audioChannelFormatName="objet 1" typeDefinition="Objects">
<audioBlockFormat audioBlockFormatID="AB_00031001_00000001"> rtime="00:00:00.00000" duration="00:00.00000"
                                              <position coordinate="X">-1</position>
                                              <position coordinate="Y">-0.0335</position>
                                              <position coordinate="Z">0</position>
                                              <cartesian>1</cartesian>
                                                    </audioBlockFormat>
<audioBlockFormat audioBlockFormatID="AB_00031001_00000002"> rtime="00:00:00.00000" duration="00:01.03157"
                                              <position coordinate="X">-0.0272</position>
                                              <position coordinate="Y">0.9313</position>
                                              <position coordinate="Z">0</position>
                                              <cartesian>1</cartesian>
                                                    </audioBlockFormat>
<audioBlockFormat audioBlockFormatID="AB_00031001_00000003"> rtime="00:00:01.03157" duration="00:00.64326"
                                              <position coordinate="X">1</position>
                                              <position coordinate="Y">-0.067</position>
                                              <position coordinate="Z">0</position>
                                              <cartesian>1</cartesian>
                                                    </audioBlockFormat>
</audioChannelFormat>
<audioChannelFormat audioChannelFormatID="AC_00031002" audioChannelFormatName="objet 2" typeDefinition="Objects">
<audioBlockFormat audioBlockFormatID="AB_00031002_00000001"> rtime="00:00:00.00000" duration="00:00.00000"
                                              <position coordinate="X">-1</position>
                                              <position coordinate="Y">-0.0335</position>
                                              <position coordinate="Z">0</position>
                                              <cartesian>1</cartesian>
                                                    </audioBlockFormat>
<audioBlockFormat audioBlockFormatID="AB_00031002_00000002"> rtime="00:00:00.00000" duration="00:01.03157"
                                              <position coordinate="X">-0.0272</position>
                                              <position coordinate="Y">0.9313</position>
                                              <position coordinate="Z">0</position>
                                              <cartesian>1</cartesian>
                                                    </audioBlockFormat>
<audioBlockFormat audioBlockFormatID="AB_00031002_00000003"> rtime="00:00:01.03157" duration="00:00.64326"
                                              <position coordinate="X">1</position>
                                              <position coordinate="Y">-0.067</position>
                                              <position coordinate="Z">0</position>
                                              <cartesian>1</cartesian>
                                                    </audioBlockFormat>
</audioChannelFormat>
<audioStreamFormat audioStreamFormatID="AS_00031001" audioStreamFormatName="objet 1" formatLabel="0001" formatDefinition="PCM">
          <audioChannelFormatIDRef>AC_00031001</audioChannelFormatIDRef>
          <audioTrackFormatIDRef>AT_00031001_01</audioTrackFormatIDRef>
          </audioStreamFormat>
<audioStreamFormat audioStreamFormatID="AS_00031002" audioStreamFormatName="objet 2" formatLabel="0001" formatDefinition="PCM">
          <audioChannelFormatIDRef>AC_00031002</audioChannelFormatIDRef>
          <audioTrackFormatIDRef>AT_00031002_01</audioTrackFormatIDRef>
          </audioStreamFormat>
<audioTrackFormat audioTrackFormatID="AT_00031001_01" audioTrackFormatName="objet 1" formatLabel="0001" formatDefinition="PCM">
                         <audioStreamFormatIDRef>AS_00031001</audioStreamFormatIDRef>
                         </audioTrackFormat>
<audioTrackFormat audioTrackFormatID="AT_00031002_01" audioTrackFormatName="objet 2" formatLabel="0001" formatDefinition="PCM">
                         <audioStreamFormatIDRef>AS_00031002</audioStreamFormatIDRef>
                         </audioTrackFormat>
<audioTrackUID UID="ATU_00000001" sampleRate="48000" bitDepth="16"/>
                    <audioTrackFormatIDRef>AT_00031001_01</audioTrackFormatIDRef>
          <audioPackFormatIDRef>AP_00031001</audioPackFormatIDRef>
<audioTrackUID UID="ATU_00000002" sampleRate="48000" bitDepth="16"/>
                    <audioTrackFormatIDRef>AT_00031002_01</audioTrackFormatIDRef>
          <audioPackFormatIDRef>AP_00031002</audioPackFormatIDRef>
</audioFormatExtended>
    </format>
  </coreMetadata>
</ebuCoreMain>

ear-utils dump chna :
AudioID(trackIndex=1, audioTrackUID='ATU_00000001', audioTrackFormatIDRef='AT_00031001_01', audioPackFormatIDRef='AP_00031001')
AudioID(trackIndex=2, audioTrackUID='ATU_00000002', audioTrackFormatIDRef='AT_00031002_01', audioPackFormatIDRef='AP_00031002')

I do not know if the axml is correct.

**Comment by firthm01** [comment]
Resolved via email
