### ISSUE TITLE
Windows build - RelWithDebInfo links wrong lib

### ISSUE THREAD

**Issue by rsjtaylor** [ebu/ear-production-suite#35]
Links fmtd.lib rather than fmt.lib when using vcpkg on Windows. Linker complains and build fails.

From gitlab 137

**Comment by rsjtaylor** [comment]
I think this issue was present when building from a msvc project (I've built succesfully via ninja) - needs verifying as vcpkg has been updated since issue submitted.

**Comment by firthm01** [comment]
No longer an issue using VCPKG version 2020.06.15
