### ISSUE TITLE
Take into account tail length when adding final automation point for parameters on export

### ISSUE THREAD

**Issue by rsjtaylor** [ebu/ear-production-suite#46]
Matt Firth:
> Create final point for all parameters
>
> We should ensure a final point for each parameter is present just prior to export. This is particularly important where we have no automation data because the set parameters may not be default, but we set just one blockFormat of duration 0 which effectively means the set values immediately get replaced by defaults anyway. Use double GetProjectLength(ReaProject* proj ) to determine where the final point should lie.
>
>code template:
```c++
if(points.size() > 0){
    auto lastPoint = points.back();
    auto projLength = api.GetProjectLength(nullptr);
    if(lastpoint.effectiveTime < projLength) {
        // Need a point
        newParameterPoint(parameter, projLength, lastPoint.value);
    }
} else {
    // No point needed - we aren't setting this parameter anyway
}
```
> Something like that in CumulatedPointsData should do it (I think there's some "finalise" methods to put it in)

...

> After [merged PR on previous repo] we will still need to do some work afterwards as we should really take in to account the "tail" length in the render dialog when calculating the final point position, but this should work for now.

From gitlab 60

**Comment by merktj** [comment]
I think the tail length for rendering should be taken into account at the following position:
https://github.com/ebu/ear-production-suite/blob/420aeed5b348f8422640cb1ba98ad395c96fef7d/reaper-adm-extension/src/reaper_adm/exportaction_admsource-earvst.cpp#L174
To get the tail length, the [latest REAPER API v6.23](https://github.com/justinfrankel/reaper-sdk/blob/main/sdk/reaper_plugin_functions.h) offers `GetSetProjectInfo(ReaProject* project, const char* desc, double value, bool is_set)` function.
However, sadly this function was introduced with version [6.01](https://mespotin.uber.space/Ultraschall/PreRelease/Reaper_Api_Documentation.html#GetSetProjectInfo) and with the currently used [API v5.961/x64](https://github.com/ebu/ear-production-suite/blob/main/reaper-adm-extension/src/reaper_adm/reaper_plugin_functions.h) I don't see an other way to get the tail length.
