### ISSUE TITLE
Investigate / fix block time rounding errors

### ISSUE THREAD

**Issue by rsjtaylor** [ebu/ear-production-suite#47]
Just noticed that when using ADM paramater in automation curves, the EAR python renderer is complaining about different blockformat rtimes:
"UserWarning: (rtime + duration) of block format AB_00031002_00000007 does not equal rtime of block format AB_00031002_00000008."
Is this a (new) issue with the EPS or rather due to a different interpretation / implementation in the python reference?

**Comment by firthm01** [comment]
Error introduced here: https://github.com/ebu/ear-production-suite/blob/1c9b87a1782b46be26e462d4cbe6290a370470bd/reaper-adm-extension/src/reaper_adm/exportaction_parameterprocessing.cpp#L482-L483

Just stick with chrono objects whilst doing arithmetic and only convert after
