### ISSUE TITLE
YOUR ADM BWF EXPORT FUNCTION FOR REAPER IS NO LONGER WORKING CORRECTLY

### ISSUE THREAD

**Issue by mpsrikar** [ebu/ear-production-suite#51]
I downloaded your suite 15 days ago.... for reaper, windows 10. I completed making an object-based audio mix using EAR production suite just yesterday. Now i exported it in Adm bwf 38 channels wav. I decided to encode it to Dolby Atmos. But the dolby atmos conversion tool is not recognizing your exported adm bwf format of EAR production suite from reaper. Dolby Atmos conversion tool is not able to recognize it and says track sample rate and ADMs sample rate mismatch error. On the other hand, when i export the same ADM mix to other object-based audio production tools like Orphus ircam admix renderer it doesn't even play it. So, what's the use of creating an object based 25 minutes film audio mix using EAR production suite when at encoding stage it doesn't properly encode ADM where other software's just simply rejecting it.... Your software is able to open other adm mixes from other production tools like Dolby Atmos production suite for example where we can clearly read and write automations to objects but when it comes to encoding or exporting stage your adm export might have some bug. Please check that reaper adm extension once again. Alas when there is no way that i can encode my immersive audio mix to Dolby atoms simple because of this adm recognizing issue, the chain is stopped. now i can't send my mix to any of my clients. Alas i have to convert my object based to channel based 5.1. No use of preparing an object-based mix using EAR production suite when it ultimately lands to a channel-based mix that too less than 10 channels because neither windows or mac os support or recognize more than 10 channel wav files . That means if i create and record a channel based 3d mix like 7.1.4, a 10-channel wav file using spat revolution, it's no use because for channel-based content can only support upto 7.1 wav in windows and mac not yet 3d for now. I tried; we can't play at least 12-channel wav file on any consumer media playback systems to experience 3d.  a 24 channel NHK 22.2 channel based immersive audio mix will definitely won't play unless until you encode such wav files to Dolby Atmos etc. For only you can deliver 5.1 successfully if you think of channel based.  Hence ADM is very important and the only way if you want to convey your object-based audio mix not even ambisonics 7th order..... I am very disappointed to find that not working. Please fix this. Okay if this a problem with Dolby Atmos production suite or Admix renderer from ircam as they are unable to recognize your adm then tell me a way such that i should take an Adm mix out of EAR production suite and encode it such that my clients should listen my hardly worked and created 38 channel object-based audio mix on their 7.1.4 speaker system or any pair of headphones! as everybody says.... . There was a serious hard work involved and i did with musical perspective that is aimed at user's natural and realistic immersion into soundscapes rather than just playing with objects . Alas i have to end up with 5.1 . So please look into this issue and its compatibility with DAPS .....

**Comment by junh1024** [comment]
Reproducing my own post,
  
"ADM was supposed to be a universal standard. However, the current situation is far from ideal. Different tools support different subsets, creating incompatibility. There are currently  multiple "types":
  
  - EBU EAR ADM using egocentric/polar/circular coordinates hereby abbreviated to EDM
  - Dolby ADM using allocentric/cartesian/cubular coordinates hereby abbreviated to DDM
  
  Currently, you can only make EDM in RPR using EAR. https://github.com/ebu/ear-productio...-still-missing 
  
  The Dolby encoder only accepts DDM, which can only be made using tools like DaVinci Resolve 17 Studio. So it would be nice to make DDM in RPR (especially since reasurround seems to be using a cubular coordinate system) so that I can make (more) deliverables for Dolby Audio in RPR, instead of using other heavyweight tools."

As a workaround can you render  514. That's directly accepted by the Dolby Encoder for EC3 Atmos.

- Would be nice if EBU devs also support DDM.
- You can also add your support for DDM support in REAPER by quoting my post and making a reply:  https://forum.cockos.com/showpost.php?p=2408066&postcount=572

**Comment by mpsrikar** [comment]
What? what workaround? So, you are telling me to make a 5.1.4 channel print from EBU reaper and upload that 10 channels wav file to a dolby encoder? Or other? Please explain clearly to render this of my object-based audio to DAPS. I don't want to convert it to a channel based even if it's a 3d channel print. Because translating it to a dolby atmos equipped cinema theatre means that my mix will be decoded to an array of speakers and no more behaves like pin point object and the same old story dares back of sweet spot and resolution and phase problems of olden, 5.1, 7.1 systems etc.

**Comment by mpsrikar** [comment]
okay here is my demo object-based audio mix. I remixed this in immersive object-based audio using the stems provided on a VIRPP remix contest platform. for ease of monitoring, i am giving you this immersive stereo format. i.e. This is in 3D BINAURAL format so use your headphones for evaluation.

This of my example remix sounds punchier and crispier due to the usage of nearfield HRTF synthesis. The most important and interesting part is this time i had fun with audio objects bouncing stuffs all around. There are many sounds in this song that i have dynamically moved which were originally placed static by the author. The user entertainment takes are as follows ..... Song contains 2 different synths originally out of which 1 synth i made it so ambient as it almost sounds as granular synthesis and ASMR type of wavy texture that is more appreciated towards end of song but originally it was missing but still there by authors. The second synth which was originally panned hard left by author that starts somewhere in middle in compliment to a trombone but is contains a frequency sweep. So now i took the advantage of that frequency sweep to further enhance it while panning it upwards. The synth now starts at left back and slowly moves upwards shooting directly above head during its sweep and then suddenly falling off again at left back and this process cycles. Binaurally we hear sounds from above with high frequencies hence i got the idea and tool the advantage of frequency sweep to pan things from bottom to top in left back and the results are literally so epic as real making the effect obvious which is very entertaining and fun user experience ultimately. Secondly there are Orgon sounds that feels like being pushed and swept away from right to left top and some funny fx sounds that are auto panned with lush reverb for lazy sounds like trombone's etc. that are left statically positioned right back as author intended.
QA whether you are able to appreciate the ADSR and that cool panning .

 Google drive link is attached
 
 [https://drive.google.com/file/d/1mji5pp9YlYC7nmfFrDLRlCXblpg-4UDO/view?usp=sharing](url)
